default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: grocery_delivery_development

test:
  <<: *default
  database: grocery_delivery_test

production:
  <<: *default
  database: grocery_delivery_production
  username: grocery_delivery
  password: <%= ENV['GROCERY_DELIVERY_DATABASE_PASSWORD'] %>
  host: <%= ENV['GROCERY_DELIVERY_DATABASE_HOST'] %>
  port: <%= ENV['GROCERY_DELIVERY_DATABASE_PORT'] %>
